# Generated by Django 5.1.2 on 2024-11-24 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='acting_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('phone_number', models.IntegerField()),
                ('landline_number', models.IntegerField()),
                ('available', models.BooleanField()),
                ('approved', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('poster', models.CharField(max_length=255)),
                ('done', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='building_style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_style', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='building_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contry', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='role_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('phone_number', models.IntegerField()),
                ('landline_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='actor_acting_types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acting_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.acting_type')),
                ('actor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.actor')),
            ],
        ),
        migrations.AddField(
            model_name='actor',
            name='current_country_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.countries'),
        ),
        migrations.CreateModel(
            name='filming_location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('detailed_address', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=255)),
                ('building_style_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.building_style')),
                ('building_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.building_type')),
                ('building_owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
        migrations.CreateModel(
            name='booking_dates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.filming_location')),
            ],
        ),
        migrations.CreateModel(
            name='location_photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(max_length=255)),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.filming_location')),
            ],
        ),
        migrations.CreateModel(
            name='location_videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.CharField(max_length=255)),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.filming_location')),
            ],
        ),
        migrations.CreateModel(
            name='official_document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.CharField(max_length=255)),
                ('actor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.actor')),
            ],
        ),
        migrations.CreateModel(
            name='artwork_gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artwork_name', models.CharField(max_length=255)),
                ('poster', models.CharField(max_length=255)),
                ('character_name', models.CharField(max_length=255)),
                ('actor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.actor')),
                ('role_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.role_type')),
            ],
        ),
        migrations.CreateModel(
            name='artwork_actors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField()),
                ('actor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.actor')),
                ('artwork_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.artwork')),
                ('role_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.role_type')),
            ],
        ),
        migrations.CreateModel(
            name='scenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scene_number', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('done', models.BooleanField()),
                ('artwork_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.artwork')),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.filming_location')),
            ],
        ),
        migrations.CreateModel(
            name='scene_actors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.actor')),
                ('scene_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.scenes')),
            ],
        ),
        migrations.CreateModel(
            name='favoraites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.filming_location')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
        migrations.AddField(
            model_name='artwork',
            name='director_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user'),
        ),
    ]
