# Generated by Django 5.1.4 on 2024-12-06 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
