# Generated by Django 5.1.4 on 2024-12-06 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_building_style_building_style_buildingstyle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building_style',
            old_name='buildingStyle',
            new_name='buildingstyle',
        ),
    ]
