# Generated by Django 5.1.4 on 2024-12-06 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_buildingstyle_building_style_buildingstyle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building_style',
            old_name='buildingstyle',
            new_name='building_style',
        ),
    ]
