# Generated by Django 5.1.4 on 2024-12-07 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_buildingtype_building_type_building_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='acting_type',
            new_name='ActingType',
        ),
        migrations.RenameModel(
            old_name='building_type',
            new_name='BuildingStyle',
        ),
        migrations.RenameModel(
            old_name='building_style',
            new_name='BuildingType',
        ),
        migrations.RenameModel(
            old_name='role_type',
            new_name='RoleType',
        ),
        migrations.RenameField(
            model_name='buildingstyle',
            old_name='building_type',
            new_name='building_style',
        ),
        migrations.RenameField(
            model_name='buildingtype',
            old_name='building_style',
            new_name='building_type',
        ),
    ]
