# Generated by Django 5.1.4 on 2024-12-07 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_acting_type_actingtype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor_additional_info',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='actor_additional_info',
            name='available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='artwork_actors',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='filming_location',
            name='building_style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.buildingstyle'),
        ),
        migrations.AlterField(
            model_name='filming_location',
            name='building_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.buildingtype'),
        ),
    ]
