# Generated by Django 5.1.4 on 2024-12-07 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_actor_additional_info_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenes',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.filming_location'),
        ),
    ]
