# Generated by Django 5.1.4 on 2024-12-07 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_scenes_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenes',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
