# Generated by Django 5.1.4 on 2024-12-23 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_scenes_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='poster',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='artwork_gallery',
            name='poster',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='location_photos',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='location_videos',
            name='video',
            field=models.ImageField(blank=True, upload_to='videos/'),
        ),
    ]
