# Generated by Django 5.1.4 on 2024-12-30 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_location_photos_photo_and_more'),
        ('core', '0020_alter_actor_additional_info_actor'),
    ]

    operations = [
    ]
