# Generated by Django 5.1.4 on 2025-02-09 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_story_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story_board',
            name='image_base64',
            field=models.FileField(upload_to='story_board/'),
        ),
    ]
