# Generated by Django 5.1.4 on 2025-02-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_story_board_image_base64'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story_board',
            name='image_base64',
            field=models.ImageField(upload_to='story_board/'),
        ),
    ]
