# Generated by Django 5.1.4 on 2025-02-11 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_story_board_image_base64'),
    ]

    operations = [
        migrations.CreateModel(
            name='trailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.CharField(max_length=255)),
                ('trailer', models.FileField(upload_to='trailer/')),
                ('video_duration', models.IntegerField()),
                ('num_scenes', models.IntegerField()),
                ('text_idea', models.CharField(max_length=255)),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
