# Generated by Django 5.1.4 on 2025-02-12 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_trailer'),
    ]

    operations = [
        migrations.CreateModel(
            name='sync_lips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='trailer/')),
                ('text', models.CharField(max_length=255)),
                ('generated_video', models.FileField(upload_to='trailer/')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
