# Generated by Django 5.1.4 on 2025-02-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_sync_lips'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sync_lips',
            name='generated_video',
            field=models.FileField(upload_to='sync_lips_output/'),
        ),
        migrations.AlterField(
            model_name='sync_lips',
            name='video',
            field=models.FileField(upload_to='sync_lips_input/'),
        ),
    ]
