# Generated by Django 5.1.4 on 2025-02-13 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_camera_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='chroma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='chroma_input/')),
                ('generated_image', models.ImageField(upload_to='chroma_output/')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
